<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tasks_container_tasks</name>
   <tag></tag>
   <elementGuidId>8913ca68-6aa2-4f35-9371-5460d94734c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container_tasks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#container_tasks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>020d51e3-b9e3-4857-912f-1021020177f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>container_tasks</value>
      <webElementGuid>1cd10f28-a882-4090-a24e-3f725f9f3569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container_tasks&quot;)</value>
      <webElementGuid>07393397-eaad-4c87-aa22-cc0031067667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0602cec6-a42b-4bfa-bb67-99dc2ca6f5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>container_tasks</value>
      <webElementGuid>fcfd0093-8b0f-4d1c-83fd-fe244f204a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container_tasks&quot;)</value>
      <webElementGuid>b90d9008-4a6a-4907-affd-7dfce9934e16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='container_tasks']</value>
      <webElementGuid>3c80b8d9-d626-47e1-9371-2469e2e32760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='topnav']/tbody/tr/td[4]/a/div[2]</value>
      <webElementGuid>35a4a2a2-a07e-4aae-bbd9-f91c0d0e02b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a/div[2]</value>
      <webElementGuid>e6487900-2474-4761-b6af-d3214737c8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'container_tasks']</value>
      <webElementGuid>31eefbc8-4507-4dea-8070-2f7a5bba7c8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
