<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginTestWithDDT</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c764b9d9-29f7-4e6d-adf6-576ce3763748</testSuiteGuid>
   <testCaseLink>
      <guid>0bb4f490-4934-4b63-8d49-00a0f852ad0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PracticeTestCases/LoginTestWithTestData</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a7cda9a3-6730-43e3-be9c-6be2eb7aa27c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Demo</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a7cda9a3-6730-43e3-be9c-6be2eb7aa27c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>65c9fc47-d207-40ba-ba2a-0d6e9a00057b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a7cda9a3-6730-43e3-be9c-6be2eb7aa27c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>c4e7b230-640c-4bcd-8756-a3651d23cf5b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
