<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_samsung a13</name>
   <tag></tag>
   <elementGuidId>c56cebfa-deed-4b0e-b9fb-aab9d44e510d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div[2]/div[2]/form/ul/li[3]/div/a/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f62be8f1-62f1-4575-80ee-1fe875f512b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lrtEPN _17d0yO</value>
      <webElementGuid>b1f8ec77-f4fb-4473-a9fa-83437f876f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>samsung a13</value>
      <webElementGuid>6ce01a2d-a8b6-4c5f-a318-73bc48e96359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_1kfTjk&quot;]/div[@class=&quot;_1rH5Jn&quot;]/div[@class=&quot;_2Xfa2_&quot;]/div[@class=&quot;_1cmsER&quot;]/form[@class=&quot;_2M8cLY header-form-search&quot;]/ul[@class=&quot;col-12-12 _1MRYA1 _38UFBk&quot;]/li[@class=&quot;Y5N33s&quot;]/div[1]/a[@class=&quot;_3izBDY&quot;]/div[@class=&quot;lrtEPN _17d0yO&quot;]</value>
      <webElementGuid>1096f806-85d0-4d76-95c4-11b9b8343462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[2]/div[2]/form/ul/li[3]/div/a/div[2]</value>
      <webElementGuid>84a99d29-fce7-4380-be50-b38d3c1f2950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='samsung'])[2]/following::div[4]</value>
      <webElementGuid>5632c341-cabd-4878-b947-b6382a8d1691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='a13']/parent::*</value>
      <webElementGuid>c772d3af-8813-4ebe-81b9-c3e80249faaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a/div[2]</value>
      <webElementGuid>6e9c9690-498e-4eec-b5c0-148be98d37e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'samsung a13' or . = 'samsung a13')]</value>
      <webElementGuid>3358d01b-9bed-490c-a142-81bba885b770</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
