<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_trainee_pwd</name>
   <tag></tag>
   <elementGuidId>0178acbe-c395-44c8-a0d5-ea7488a3135c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pwd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pwd&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59fc4e22-1c91-40e7-aa0e-87624d953078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0342f370-68b1-49ce-81ed-eaba6ebf9a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pwd</value>
      <webElementGuid>dd2b04e5-0b9e-41ad-9371-e4d72636afb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textField pwdfield</value>
      <webElementGuid>0cbdb508-6428-4dcc-9654-b2b1793b0a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>3205f3cc-f52e-473d-9949-657f62b900eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginFormContainer&quot;)/tbody[1]/tr[1]/td[@class=&quot;textFieldsArea&quot;]/table[@class=&quot;textFieldsTable&quot;]/tbody[1]/tr[2]/td[1]/input[@class=&quot;textField pwdfield&quot;]</value>
      <webElementGuid>ed316347-5946-4c55-9761-bcc3652322d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e440ee8-fe39-4b6e-b875-1609acaa99e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ed3aa384-e801-4539-a6ae-d32669618be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pwd</value>
      <webElementGuid>e29a91fa-8050-457e-8548-c75614cefc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textField pwdfield</value>
      <webElementGuid>203f9bdf-88e9-4adc-8fbb-1dd0acaccbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>cb1ff4e7-4e11-4b10-8be7-83efff226956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginFormContainer&quot;)/tbody[1]/tr[1]/td[@class=&quot;textFieldsArea&quot;]/table[@class=&quot;textFieldsTable&quot;]/tbody[1]/tr[2]/td[1]/input[@class=&quot;textField pwdfield&quot;]</value>
      <webElementGuid>4710f3be-7fb6-4ea6-85bc-c2bdc5d59074</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pwd']</value>
      <webElementGuid>936fea9a-fa34-4f54-a54a-8f55ddd922a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='loginFormContainer']/tbody/tr/td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>163fecd7-90fc-4c96-b264-5bc6285620df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>47f901a5-e0f9-43ce-b777-8b02bc05a894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'pwd' and @placeholder = 'Password']</value>
      <webElementGuid>8b294f76-28cf-474f-8298-f8d0b2ea1fd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
