<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Samsung</name>
   <tag></tag>
   <elementGuidId>f2eb9cf0-9acb-488f-a56a-543b58678a91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='body']/aside/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.brandmenu-v2.light.l-box.clearfix > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>586eab70-104e-4d30-a85b-b1cd1ac0d181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>samsung-phones-9.php</value>
      <webElementGuid>52cfeedc-3e9d-42e2-8101-6986eaef751e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samsung</value>
      <webElementGuid>51a36e57-4ee0-40a3-a654-c0ff018d4d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/aside[@class=&quot;sidebar col left&quot;]/div[@class=&quot;brandmenu-v2 light l-box clearfix&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>6ecd6c86-ae5f-4874-acd9-6e9694260c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c016834-c7b8-4edc-8c5d-3216aa8c01d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>samsung-phones-9.php</value>
      <webElementGuid>f320dd1a-0e47-40e4-a039-aa2e9bcc7523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samsung</value>
      <webElementGuid>47e2f362-f280-40da-bf30-d76055c970d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/aside[@class=&quot;sidebar col left&quot;]/div[@class=&quot;brandmenu-v2 light l-box clearfix&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>c60250af-d5e9-417c-b4dc-67b5428ad64e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body']/aside/div/ul/li/a</value>
      <webElementGuid>557ddcf6-eaa9-436e-90eb-49b0f443cf6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Samsung')]</value>
      <webElementGuid>db41ab10-d5ef-4dd8-8b2d-840c1663462d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone finder'])[1]/following::a[1]</value>
      <webElementGuid>7d9efb78-e38f-4620-a257-4d6e5481fb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Motorola Edge (2022) renders surface along with confirmation of the rumored specs'])[1]/following::a[3]</value>
      <webElementGuid>f6cd1901-7b4a-4eea-97e2-b043831b7a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple'])[1]/preceding::a[1]</value>
      <webElementGuid>ad500d17-a735-442a-8930-9863d3c7714a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Huawei'])[1]/preceding::a[2]</value>
      <webElementGuid>27645970-fdc4-4313-a005-1723424fcbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Samsung']/parent::*</value>
      <webElementGuid>6e86c2cd-77b9-4bbe-83b8-8721efd4bacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'samsung-phones-9.php')]</value>
      <webElementGuid>91a7a9c6-20d2-4b99-bd8b-45c6189a1b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/ul/li/a</value>
      <webElementGuid>2a44276f-2f77-4777-af24-98fb94c3f2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'samsung-phones-9.php' and (text() = 'Samsung' or . = 'Samsung')]</value>
      <webElementGuid>b7b61486-3c16-43b2-910a-eac70831c253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
