<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_samsung mobilesin Mobiles</name>
   <tag></tag>
   <elementGuidId>48111fc5-f1cd-4e92-b6fe-bc5c80c45444</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/search?q=samsung+mobiles&amp;sid=tyy%2C4io&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=samsung+mobiles%7CMobiles&amp;requestId=8dfccb7b-dd10-40ec-8671-00833615dc9b&amp;as-searchtext=samsung%20' and (text() = 'samsung mobilesin Mobiles' or . = 'samsung mobilesin Mobiles')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div[2]/div[2]/form/ul/li/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a._3izBDY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d1160b5-b06f-4055-8c6d-d5e5dcefdea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3izBDY</value>
      <webElementGuid>12eae944-1115-440e-b40c-e7bd10f0fd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search?q=samsung+mobiles&amp;sid=tyy%2C4io&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=samsung+mobiles%7CMobiles&amp;requestId=8dfccb7b-dd10-40ec-8671-00833615dc9b&amp;as-searchtext=samsung%20</value>
      <webElementGuid>9cef373e-b255-40d7-806a-86f584e9e5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>samsung mobilesin Mobiles</value>
      <webElementGuid>1f038a34-b3c1-491c-a4ac-3d45a54240e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_1kfTjk&quot;]/div[@class=&quot;_1rH5Jn&quot;]/div[@class=&quot;_2Xfa2_&quot;]/div[@class=&quot;_1cmsER&quot;]/form[@class=&quot;_2M8cLY header-form-search&quot;]/ul[@class=&quot;col-12-12 _1MRYA1 _38UFBk&quot;]/li[@class=&quot;Y5N33s&quot;]/div[1]/a[@class=&quot;_3izBDY&quot;]</value>
      <webElementGuid>776c7bd7-cc25-456d-b62c-313e4dc64b71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[2]/div[2]/form/ul/li/div/a</value>
      <webElementGuid>cf56f629-6843-4513-be82-db51827e03fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plus'])[1]/following::a[1]</value>
      <webElementGuid>8f468370-3dd3-4a2a-ad85-c9cca32e2324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search?q=samsung+mobiles&amp;sid=tyy%2C4io&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=samsung+mobiles%7CMobiles&amp;requestId=8dfccb7b-dd10-40ec-8671-00833615dc9b&amp;as-searchtext=samsung%20')]</value>
      <webElementGuid>2d8673d3-968e-4d45-ac22-c4195495630b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/a</value>
      <webElementGuid>e1af385f-d7c9-4c80-bf27-54422e9aeb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search?q=samsung+mobiles&amp;sid=tyy%2C4io&amp;as=on&amp;as-show=on&amp;otracker=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&amp;otracker1=AS_QueryStore_OrganicAutoSuggest_1_8_na_na_na&amp;as-pos=1&amp;as-type=RECENT&amp;suggestionId=samsung+mobiles%7CMobiles&amp;requestId=8dfccb7b-dd10-40ec-8671-00833615dc9b&amp;as-searchtext=samsung%20' and (text() = 'samsung mobilesin Mobiles' or . = 'samsung mobilesin Mobiles')]</value>
      <webElementGuid>bd9b446a-a23a-4087-982a-c11c864e03a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
