<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Type of Work_descriptionElement</name>
   <tag></tag>
   <elementGuidId>96b630c3-9d93-4445-a1a9-df6acf3a69a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='descriptionElement']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#descriptionElement</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7bfc9158-8b20-4f5b-ab30-f79d651f341a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descriptionElement</value>
      <webElementGuid>71f0d4ae-d4e0-44cd-b892-d32ab172906c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>cfd79ab1-da51-4437-afae-d50fb170202b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to enter task description</value>
      <webElementGuid>88a075a0-7959-47c3-8e05-a18121cab9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descriptionCell0&quot;)/a[@id=&quot;descriptionElement&quot;]</value>
      <webElementGuid>4d164198-3903-4736-8821-da2467a28956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38b2da4a-bf82-426e-81f2-94c8a4bbaec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descriptionElement</value>
      <webElementGuid>61e075c4-d96a-496d-a985-0049ebbdca5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ab7a9763-ce6d-4b0a-8fbe-09db341d6b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to enter task description</value>
      <webElementGuid>977b8c98-a794-4d61-aefd-3e528f8da1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descriptionCell0&quot;)/a[@id=&quot;descriptionElement&quot;]</value>
      <webElementGuid>e3b8514d-4581-4e27-8614-e4dcae848cf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='descriptionElement']</value>
      <webElementGuid>b39ae7e2-ea52-49d0-83c6-0ae7e7cfde16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='descriptionCell0']/a</value>
      <webElementGuid>8b323131-a218-4b7b-9f71-470f6661f5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Work'])[8]/following::a[1]</value>
      <webElementGuid>c50607c7-20bd-4a8b-ae1f-e05fac8af1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deadline'])[3]/following::a[1]</value>
      <webElementGuid>23894bfd-5a03-44a4-a1ed-0c4d1d82725c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aug 19, 2022'])[10]/preceding::a[1]</value>
      <webElementGuid>a60f0d85-4cf5-4e1c-b5dc-5aa6093a7bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NON-BILLABLE:'])[4]/preceding::a[1]</value>
      <webElementGuid>d07c0b00-c169-4d52-9b10-b5e5d31e8d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>adf74f31-13d2-4f68-9f95-d32994a15ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/a</value>
      <webElementGuid>38f34a93-4535-4908-bf9e-ff5e46f49b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'descriptionElement' and @href = '#' and @title = 'Click to enter task description']</value>
      <webElementGuid>5c862d20-c995-4792-82f3-9d710b8dfac0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
