<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Delete</name>
   <tag></tag>
   <elementGuidId>03155bac-2d44-4973-891e-55ba309ec68c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='taskListBlock']/div[4]/div/div/div/div/div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.delete.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c2721fc-1114-47eb-bbba-5c006a4839b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delete button</value>
      <webElementGuid>7b2c58c5-1613-4039-9093-db1e05f8067e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>1fe1c432-dd01-4bf9-8595-18c5c6004517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taskListBlock&quot;)/div[@class=&quot;animatedVisibilityContainer tasklist_components_bulkOperationsPanelContainer&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;loadingContainer&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;bulkOperationsPanel&quot;]/div[@class=&quot;delete button&quot;]</value>
      <webElementGuid>94199a97-9739-4c37-bb11-0079ea792182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>31cefe67-b276-49f8-b486-7a101809682a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delete button</value>
      <webElementGuid>02fbfb4d-fc87-4504-af74-02a33cbce9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>4f21b3b2-bf74-44d5-a3ec-a67ea6284baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taskListBlock&quot;)/div[@class=&quot;animatedVisibilityContainer tasklist_components_bulkOperationsPanelContainer&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;loadingContainer&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;bulkOperationsPanel&quot;]/div[@class=&quot;delete button&quot;]</value>
      <webElementGuid>0159472a-ee62-4407-94bc-8c45c168dd9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='taskListBlock']/div[4]/div/div/div/div/div[6]</value>
      <webElementGuid>68207e2a-b187-42b0-912a-df6e89517c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Status'])[1]/following::div[1]</value>
      <webElementGuid>aa73cfd5-0558-438b-8082-5c11c8aa2a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign to'])[1]/following::div[2]</value>
      <webElementGuid>3e6bcd95-8eb2-4295-b59d-cf1f3062aeb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear selection'])[1]/preceding::div[1]</value>
      <webElementGuid>ad5b94bb-61c6-43b1-be48-f9177c74bac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[4]/preceding::div[4]</value>
      <webElementGuid>23207df4-2eb0-402e-a992-6155485c7748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete']/parent::*</value>
      <webElementGuid>c7ebdd78-eb8d-4451-82af-1735c8004a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[6]</value>
      <webElementGuid>5feacaa4-5bad-41cf-b69e-41fc2ffe7bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>c79cd1d2-a520-4e47-ad89-b6255bea650b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
