<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_- Select Customer -</name>
   <tag></tag>
   <elementGuidId>b0f5172d-b591-4688-81b0-a37ad63f0a32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '- Select Customer -' or . = '- Select Customer -')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='createTasksPopup_content']/div/div/div/div/div/table/tbody/tr/td/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.emptySelection</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>936a7082-10a0-4fe9-b86f-ac0ebaf8f4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>emptySelection</value>
      <webElementGuid>81a3549d-3cdc-4d78-a369-197d6e9110cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Select Customer -</value>
      <webElementGuid>19d0ac52-b6c3-48d1-944f-f04a53ee86d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createTasksPopup_content&quot;)/div[@class=&quot;scrollableContainer&quot;]/div[@class=&quot;contentWrapper&quot;]/div[@class=&quot;innerContent&quot;]/div[@class=&quot;customerProjectSelectorPlaceholder&quot;]/div[@class=&quot;selectCustomerAndProject&quot;]/table[1]/tbody[1]/tr[@class=&quot;selectCustomerRow&quot;]/td[1]/div[@class=&quot;customerSelector customerOrProjectSelector selectorWithPlaceholderContainer&quot;]/div[@class=&quot;components_combobox cpCombobox&quot;]/div[@class=&quot;comboboxButton&quot;]/div[@class=&quot;selectedItem&quot;]/div[@class=&quot;emptySelection&quot;]</value>
      <webElementGuid>90a3fc1b-1ebb-4b81-af68-a2cf927c9a26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createTasksPopup_content']/div/div/div/div/div/table/tbody/tr/td/div/div/div/div/div</value>
      <webElementGuid>3d2fdc9d-a547-4a30-ad75-ce4a81936f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Customer and Project to Add Tasks for'])[1]/following::div[5]</value>
      <webElementGuid>d0439cb7-2040-4870-adbb-1245e35e9dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Tasks'])[1]/following::div[11]</value>
      <webElementGuid>311fe29d-249d-475c-817e-6a9d7ee8947e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- New Customer -'])[1]/preceding::div[6]</value>
      <webElementGuid>14879549-2458-4aa1-b072-863ec71d1cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- ALL ACTIVE CUSTOMERS -'])[1]/preceding::div[7]</value>
      <webElementGuid>b15a2a37-409b-4b16-b4f5-473d5337ca01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='- Select Customer -']/parent::*</value>
      <webElementGuid>3696cf91-8cf2-489c-a7c5-3c9379c942a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[52]/div/div/div/div/div/div/table/tbody/tr/td/div/div/div/div/div</value>
      <webElementGuid>fb2125dd-d077-447d-9524-5f55201c3256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '- Select Customer -' or . = '- Select Customer -')]</value>
      <webElementGuid>f2f4df45-9c62-4195-af9b-982d1a836a8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
