<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create Tasks</name>
   <tag></tag>
   <elementGuidId>44fd8728-4956-499b-b0f4-530cb285a77d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='createTasksPopup_content']/div[2]/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.commitButtonPlaceHolder > div.components_button.withPlusIcon > div.components_button_label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>99644cfe-23ae-410a-9bf3-6ed5f25636c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>components_button_label</value>
      <webElementGuid>cef2d49a-671a-43e4-91a2-41c59f0e94a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Tasks</value>
      <webElementGuid>2815869e-ef26-41c2-a8c1-67df7ae6874d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createTasksPopup_content&quot;)/div[@class=&quot;basicLightboxFooter&quot;]/div[@class=&quot;buttonsBox&quot;]/div[@class=&quot;commitButtonPlaceHolder&quot;]/div[@class=&quot;components_button withPlusIcon&quot;]/div[@class=&quot;components_button_label&quot;]</value>
      <webElementGuid>27f4631c-e1ad-44a2-a6e7-ebf2513112a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>493dde3d-0251-4ccd-8c8f-47f5a4aa2e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>components_button_label</value>
      <webElementGuid>dee1e33c-c009-42a4-8062-d00280944c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Tasks</value>
      <webElementGuid>aee6f346-eaf0-482b-ab16-f6947cfc33ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createTasksPopup_content&quot;)/div[@class=&quot;basicLightboxFooter&quot;]/div[@class=&quot;buttonsBox&quot;]/div[@class=&quot;commitButtonPlaceHolder&quot;]/div[@class=&quot;components_button withPlusIcon&quot;]/div[@class=&quot;components_button_label&quot;]</value>
      <webElementGuid>d266273b-6f7c-433f-8c90-2380973a82f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createTasksPopup_content']/div[2]/div[2]/div/div/div</value>
      <webElementGuid>c91b0260-09d0-43b4-ae51-e82876f1b4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVING ...'])[3]/following::div[3]</value>
      <webElementGuid>a9c1d911-8ad2-4296-824b-3f211f590a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOT SAVED'])[1]/following::div[3]</value>
      <webElementGuid>62ec093c-e7a2-4e38-a43f-08e0325855cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[28]/preceding::div[2]</value>
      <webElementGuid>e28c5b5c-9ecd-4472-801e-279dbb1766ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select customer or project'])[1]/preceding::div[3]</value>
      <webElementGuid>04f16cd4-2bdb-4349-bc40-f7ccdb2462ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Tasks']/parent::*</value>
      <webElementGuid>3ab99fce-71b2-47bb-8d9c-03c9bc23e404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[52]/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>c7a1cf9e-22d7-4b26-88da-f7c03b3531cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Create Tasks' or . = 'Create Tasks')]</value>
      <webElementGuid>2aee13ee-7322-4fc2-97c5-e1f0114da896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
