<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__img</name>
   <tag></tag>
   <elementGuidId>f7fcc8cd-4ed6-4f66-8c3f-fa2d78ccfb26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='taskListBlock']/div[2]/div/div/div/div/div/div/div/table/tbody/tr/td/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.taskRow.noLastTrackingDate > td.selection > div.checkbox.inactive > div.img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ac8073a-3646-4b93-aef3-6c45759024b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3c1e28a8-da7d-40ca-9ced-f8e3cc27fef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taskListBlock&quot;)/div[@class=&quot;tasksTable scrollToTopButtonShifted allTasksLoaded hasSelectedCustomer hasSelectedProject&quot;]/div[@class=&quot;autoScrollableWrapper scrollableContainer tasksTableHorizontalScrollableWrapper&quot;]/div[@class=&quot;innerScrollableContainer&quot;]/div[@class=&quot;autoScrollableWrapper scrollableContainer tasksTableVerticalScrollContainer&quot;]/div[@class=&quot;innerScrollableContainer&quot;]/div[@class=&quot;taskRowsTableContent&quot;]/div[@class=&quot;tasksTablesWrapper&quot;]/div[@class=&quot;createdTasksTableContainer&quot;]/table[@class=&quot;createdTasksRowsTable&quot;]/tbody[1]/tr[@class=&quot;taskRow noLastTrackingDate&quot;]/td[@class=&quot;selection&quot;]/div[@class=&quot;checkbox inactive&quot;]/div[@class=&quot;img&quot;]</value>
      <webElementGuid>82e01c1c-1319-454b-bbcd-4a6c0ce8df31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba8abc10-d67e-4dfd-9051-eabdb151c18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c19a4db7-25c1-4756-8f69-05e5ed0a4df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taskListBlock&quot;)/div[@class=&quot;tasksTable scrollToTopButtonShifted allTasksLoaded hasSelectedCustomer hasSelectedProject&quot;]/div[@class=&quot;autoScrollableWrapper scrollableContainer tasksTableHorizontalScrollableWrapper&quot;]/div[@class=&quot;innerScrollableContainer&quot;]/div[@class=&quot;autoScrollableWrapper scrollableContainer tasksTableVerticalScrollContainer&quot;]/div[@class=&quot;innerScrollableContainer&quot;]/div[@class=&quot;taskRowsTableContent&quot;]/div[@class=&quot;tasksTablesWrapper&quot;]/div[@class=&quot;createdTasksTableContainer&quot;]/table[@class=&quot;createdTasksRowsTable&quot;]/tbody[1]/tr[@class=&quot;taskRow noLastTrackingDate&quot;]/td[@class=&quot;selection&quot;]/div[@class=&quot;checkbox inactive&quot;]/div[@class=&quot;img&quot;]</value>
      <webElementGuid>cff52a02-b9ca-48d6-9ef7-ba86d7acd576</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='taskListBlock']/div[2]/div/div/div/div/div/div/div/table/tbody/tr/td/div/div</value>
      <webElementGuid>b783d8db-69e0-4032-bd50-d7392807ff55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/table/tbody/tr/td/div/div</value>
      <webElementGuid>22fcc189-c86d-4569-8986-30ce0f9e49e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
