<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add New_downIcon</name>
   <tag></tag>
   <elementGuidId>7d4c857f-361a-4b1e-be62-f941c0f9c128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='taskManagementPage']/div/div/div/div/div[3]/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.downIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07c3ce16-0a99-41aa-9640-acee29d2e340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>downIcon</value>
      <webElementGuid>9b5fe5b4-e66d-4f17-bce3-483a9e5c8b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taskManagementPage&quot;)/div[@class=&quot;cpTreeBlock ui-widget-content ui-resizable&quot;]/div[@class=&quot;customersProjectsPanel&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;titleContainer&quot;]/div[@class=&quot;addNewContainer&quot;]/div[@class=&quot;addNewButton&quot;]/div[@class=&quot;downIcon&quot;]</value>
      <webElementGuid>82495888-1e96-4d81-a961-35904524a144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>da2cf780-e785-4fd0-9d28-d8a19a5cc996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>downIcon</value>
      <webElementGuid>6ddc65b1-f59f-4f99-9888-c82d8dddeacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taskManagementPage&quot;)/div[@class=&quot;cpTreeBlock ui-widget-content ui-resizable&quot;]/div[@class=&quot;customersProjectsPanel&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;titleContainer&quot;]/div[@class=&quot;addNewContainer&quot;]/div[@class=&quot;addNewButton&quot;]/div[@class=&quot;downIcon&quot;]</value>
      <webElementGuid>4f7b7f39-1af1-4950-97d2-d507a0d60ffd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='taskManagementPage']/div/div/div/div/div[3]/div/div[3]</value>
      <webElementGuid>4f4eacd0-d122-4eaa-8964-c5b28af8e4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/div/div/div[3]/div/div[3]</value>
      <webElementGuid>c0ca4f02-33ea-4c21-bc5f-89eba2052865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
