<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Customer and Project to Add Task_c324d2</name>
   <tag></tag>
   <elementGuidId>9aaf9a36-23bd-4d6f-8c95-96367d86e03e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='createTasksPopup_content']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e652d989-9f5f-4d9c-8b2c-8c005eff9079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>innerContent</value>
      <webElementGuid>7b226945-9c9f-4be7-95d7-234cc30701f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>         Select Customer and Project to Add Tasks for                                                          Big Bang Company                          - New Customer -- ALL ACTIVE CUSTOMERS -Big Bang CompanyGalaxy CorporationOur company                                                        Please select customer                    Warning! There are no active customers                                                                                                                                Customer name cannot be empty                    Customer with the specified name already exists                                                                              Flight operations                          - New Project -- ALL ACTIVE PROJECTS -- SELECTED ACTIVE PROJECTS (by project name) -Flight operationsSpaceship buildingSpaceship testing                                                        Please select project                    Warning! There are no active projects                                                                                                                                Project name cannot be empty                    Customer already contains a project with the specified name                                                                                        Flight operations      Spaceship building      Spaceship testing                                                              Please select names of the projects to add tasks for                                                New tasks            Copy properties from existing tasks                                                                                                                        Task Name                                  Estimate                                              Deadline                                 Type of Work                                                                                        set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering            Add new row    5 rows    10 rows  </value>
      <webElementGuid>44573f64-3a5b-4db9-95c1-019f73b9ec3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createTasksPopup_content&quot;)/div[@class=&quot;scrollableContainer&quot;]/div[@class=&quot;contentWrapper&quot;]/div[@class=&quot;innerContent&quot;]</value>
      <webElementGuid>05204663-a4d0-4205-87cb-0c78193ff4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8fe5f25f-5585-4bcc-b423-72681ebb139d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>innerContent</value>
      <webElementGuid>ca9081b9-1dbe-4b34-8b21-54889d97bdf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>         Select Customer and Project to Add Tasks for                                                          Big Bang Company                          - New Customer -- ALL ACTIVE CUSTOMERS -Big Bang CompanyGalaxy CorporationOur company                                                        Please select customer                    Warning! There are no active customers                                                                                                                                Customer name cannot be empty                    Customer with the specified name already exists                                                                              Flight operations                          - New Project -- ALL ACTIVE PROJECTS -- SELECTED ACTIVE PROJECTS (by project name) -Flight operationsSpaceship buildingSpaceship testing                                                        Please select project                    Warning! There are no active projects                                                                                                                                Project name cannot be empty                    Customer already contains a project with the specified name                                                                                        Flight operations      Spaceship building      Spaceship testing                                                              Please select names of the projects to add tasks for                                                New tasks            Copy properties from existing tasks                                                                                                                        Task Name                                  Estimate                                              Deadline                                 Type of Work                                                                                        set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering            Add new row    5 rows    10 rows  </value>
      <webElementGuid>26646224-f830-45ee-a42a-bfbc58ba7b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createTasksPopup_content&quot;)/div[@class=&quot;scrollableContainer&quot;]/div[@class=&quot;contentWrapper&quot;]/div[@class=&quot;innerContent&quot;]</value>
      <webElementGuid>6dba369e-74e1-4cbc-a28e-d64056e9a39f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createTasksPopup_content']/div/div/div</value>
      <webElementGuid>11118081-a32e-4059-9751-5f9b8af011f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Tasks'])[1]/following::div[3]</value>
      <webElementGuid>94592999-b28c-446f-bc0e-6982a56b243b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='completed'])[1]/following::div[11]</value>
      <webElementGuid>33a7ff8e-884a-4556-8f93-9282a89a4357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[52]/div/div/div/div</value>
      <webElementGuid>f47771df-56c3-430d-a7a5-24710b68e33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '         Select Customer and Project to Add Tasks for                                                          Big Bang Company                          - New Customer -- ALL ACTIVE CUSTOMERS -Big Bang CompanyGalaxy CorporationOur company                                                        Please select customer                    Warning! There are no active customers                                                                                                                                Customer name cannot be empty                    Customer with the specified name already exists                                                                              Flight operations                          - New Project -- ALL ACTIVE PROJECTS -- SELECTED ACTIVE PROJECTS (by project name) -Flight operationsSpaceship buildingSpaceship testing                                                        Please select project                    Warning! There are no active projects                                                                                                                                Project name cannot be empty                    Customer already contains a project with the specified name                                                                                        Flight operations      Spaceship building      Spaceship testing                                                              Please select names of the projects to add tasks for                                                New tasks            Copy properties from existing tasks                                                                                                                        Task Name                                  Estimate                                              Deadline                                 Type of Work                                                                                        set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering            Add new row    5 rows    10 rows  ' or . = '         Select Customer and Project to Add Tasks for                                                          Big Bang Company                          - New Customer -- ALL ACTIVE CUSTOMERS -Big Bang CompanyGalaxy CorporationOur company                                                        Please select customer                    Warning! There are no active customers                                                                                                                                Customer name cannot be empty                    Customer with the specified name already exists                                                                              Flight operations                          - New Project -- ALL ACTIVE PROJECTS -- SELECTED ACTIVE PROJECTS (by project name) -Flight operationsSpaceship buildingSpaceship testing                                                        Please select project                    Warning! There are no active projects                                                                                                                                Project name cannot be empty                    Customer already contains a project with the specified name                                                                                        Flight operations      Spaceship building      Spaceship testing                                                              Please select names of the projects to add tasks for                                                New tasks            Copy properties from existing tasks                                                                                                                        Task Name                                  Estimate                                              Deadline                                 Type of Work                                                                                        set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering       set deadline     NON-BILLABLE:    non-billable    management    research    salesBILLABLE:    engineering    manufacturing    repair: complex    repair: standard    testing    support     engineering            Add new row    5 rows    10 rows  ')]</value>
      <webElementGuid>640c02e5-5cf9-4121-ba58-9c7684e31db1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
