<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>317f2377-fc0f-41f4-ada5-febb0e131449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='descriptionElement']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#descriptionElement > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d4f9fdc-3129-4fd8-bd44-0c4d0f3dd5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/default/dialogs/comments/comment_blank.png?hash=1846506722</value>
      <webElementGuid>a0e76fea-1c32-44ee-ab65-1e1d5759849f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descriptionCell0&quot;)/a[@id=&quot;descriptionElement&quot;]/img[1]</value>
      <webElementGuid>13755a78-a85b-4156-9ba6-3e21a5391284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fb72c897-ec8e-4e8c-abe9-294dacb21f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/default/dialogs/comments/comment_blank.png?hash=1846506722</value>
      <webElementGuid>cdcafe3c-f31b-4592-8990-61c5c8714558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descriptionCell0&quot;)/a[@id=&quot;descriptionElement&quot;]/img[1]</value>
      <webElementGuid>25d18378-6b2b-42a9-af8c-a4c132b952c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='descriptionElement']/img</value>
      <webElementGuid>23e34195-5ef4-4913-862b-cc2e02b9f631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>0d2737ed-dc73-417e-a6d6-b5e0d9802b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/default/dialogs/comments/comment_blank.png?hash=1846506722']</value>
      <webElementGuid>2887fabb-f838-44c6-a8e6-259a32cfd059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
