<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type of Work_inputFieldWithPlaceholder</name>
   <tag></tag>
   <elementGuidId>decaeb46-83ff-40f9-8620-56fb2a549191</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[70]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.nameCell.first > input.inputFieldWithPlaceholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1f8eb92-7049-465a-a5b5-db6ec90c0442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9bcab961-66b2-407d-8b04-edd14531cff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>4a18cba1-8559-4ebe-9a03-10630f3202e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputFieldWithPlaceholder</value>
      <webElementGuid>7083450f-241b-4c41-8c43-439f97911a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter task name</value>
      <webElementGuid>51d170f4-e098-4f63-a977-135107c02e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createTasksPopup_content&quot;)/div[@class=&quot;scrollableContainer&quot;]/div[@class=&quot;contentWrapper&quot;]/div[@class=&quot;innerContent&quot;]/div[@class=&quot;tablePlaceholder&quot;]/div[@class=&quot;taskTable&quot;]/div[@class=&quot;taskTableContainer&quot;]/table[@class=&quot;createTasksTable&quot;]/tbody[1]/tr[1]/td[@class=&quot;nameCell first&quot;]/input[@class=&quot;inputFieldWithPlaceholder&quot;]</value>
      <webElementGuid>00f2af49-2f32-4213-81d8-92110d7377e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be61d51f-b3de-417d-a00a-ae3a288c0e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>649fd84a-d28c-43d4-b09c-903801cd2143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>96a87e7b-939d-4766-b7a0-0c52b8be88f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputFieldWithPlaceholder</value>
      <webElementGuid>21be3af4-f4d9-452e-838d-16dfe8b2db4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter task name</value>
      <webElementGuid>3317555b-4be2-4056-b4f7-2d235597e76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createTasksPopup_content&quot;)/div[@class=&quot;scrollableContainer&quot;]/div[@class=&quot;contentWrapper&quot;]/div[@class=&quot;innerContent&quot;]/div[@class=&quot;tablePlaceholder&quot;]/div[@class=&quot;taskTable&quot;]/div[@class=&quot;taskTableContainer&quot;]/table[@class=&quot;createTasksTable&quot;]/tbody[1]/tr[1]/td[@class=&quot;nameCell first&quot;]/input[@class=&quot;inputFieldWithPlaceholder&quot;]</value>
      <webElementGuid>69ec7663-8c6f-4514-b9a5-b9d059ed1a15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[70]</value>
      <webElementGuid>71bc8214-9b75-49cd-aca0-d4ed62d57eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createTasksPopup_content']/div/div/div/div[3]/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>ecd43ed7-91b9-44b3-b251-e4183e34682d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>21cf5a0a-669d-427d-b6bd-24acdbfbf333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter task name']</value>
      <webElementGuid>ec06fe4d-1ab8-418c-84e3-3e4ce4336c40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
