<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type of Work_inputFieldWithPlaceholder_1</name>
   <tag></tag>
   <elementGuidId>6a219376-fc11-4929-a317-a19da5a1bef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[71]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.estimateCell > input.inputFieldWithPlaceholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10b481b3-5ea4-4cd6-8fc8-b6bc19af8a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30c7860d-c654-49da-9429-89c9438af679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2dbb78b2-570a-4e35-8563-ffe4f0f2b1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputFieldWithPlaceholder</value>
      <webElementGuid>4f07c8d6-38f6-4eef-9d3a-a81565ba2c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>not needed</value>
      <webElementGuid>691dd399-83e9-4eba-b3e7-d6ab744eb44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createTasksPopup_content&quot;)/div[@class=&quot;scrollableContainer&quot;]/div[@class=&quot;contentWrapper&quot;]/div[@class=&quot;innerContent&quot;]/div[@class=&quot;tablePlaceholder&quot;]/div[@class=&quot;taskTable&quot;]/div[@class=&quot;taskTableContainer&quot;]/table[@class=&quot;createTasksTable&quot;]/tbody[1]/tr[1]/td[@class=&quot;estimateCell&quot;]/input[@class=&quot;inputFieldWithPlaceholder&quot;]</value>
      <webElementGuid>dceaed3b-ccb4-43cc-ae62-35ba11881c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>530c957f-26e0-4e00-ad5e-5a729fa6b8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0092e22f-5b86-46fd-b739-651715d52cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>95420db9-c89b-4649-b8fe-8b721d49dae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputFieldWithPlaceholder</value>
      <webElementGuid>3bee3db8-9aa7-431c-a44d-c2f54ab81963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>not needed</value>
      <webElementGuid>b33da8b0-03a8-4891-acff-fc56b9e75621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createTasksPopup_content&quot;)/div[@class=&quot;scrollableContainer&quot;]/div[@class=&quot;contentWrapper&quot;]/div[@class=&quot;innerContent&quot;]/div[@class=&quot;tablePlaceholder&quot;]/div[@class=&quot;taskTable&quot;]/div[@class=&quot;taskTableContainer&quot;]/table[@class=&quot;createTasksTable&quot;]/tbody[1]/tr[1]/td[@class=&quot;estimateCell&quot;]/input[@class=&quot;inputFieldWithPlaceholder&quot;]</value>
      <webElementGuid>781e33d6-ee71-4083-ab76-558db64b9494</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[71]</value>
      <webElementGuid>03859dba-48f9-4320-beca-eaa4fe94292e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createTasksPopup_content']/div/div/div/div[3]/div/div/table/tbody/tr/td[3]/input</value>
      <webElementGuid>a015b8ed-36cf-4b73-9467-5034df1e9db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>0f4f7b4c-1bfc-4bc4-869a-74825e408ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'not needed']</value>
      <webElementGuid>3a7a6dd5-27f8-47ef-8cab-cdadf740d182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
