<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>d2783967-01ff-402b-8d3e-0e59b7a87640</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.searchField.focusing > table.containerTable > tbody > tr > td.inputColumn > div.cellWrapper > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f559748a-7915-4ea8-8812-7f4678e2a58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77be8615-e37e-4002-b500-2ebb2a10a16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing name ...</value>
      <webElementGuid>1a8e90b6-3aa6-4900-9b39-a0e633ad4bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e74a53d7-ca83-4fca-bc61-d0197ec37116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taskListBlock&quot;)/div[@class=&quot;taskManagementHeaderPanel hasSelectedCustomer hasSelectedProject&quot;]/div[@class=&quot;topContainer&quot;]/div[@class=&quot;rightContainer&quot;]/div[@class=&quot;searchFieldContainer&quot;]/div[@class=&quot;searchField focusing&quot;]/table[@class=&quot;containerTable&quot;]/tbody[1]/tr[1]/td[@class=&quot;inputColumn&quot;]/div[@class=&quot;cellWrapper&quot;]/input[1]</value>
      <webElementGuid>4760983f-23ba-4ff2-abb2-8e1e54527ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>106bb110-7223-4c06-8f8d-64e330429b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>547d71cb-b251-4f76-850a-fa8ebb0dbe48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing name ...</value>
      <webElementGuid>3abfb4ea-f312-49a3-a65d-a56ee8916406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>2e55776d-2168-4fb2-abcb-e64914045d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taskListBlock&quot;)/div[@class=&quot;taskManagementHeaderPanel hasSelectedCustomer hasSelectedProject&quot;]/div[@class=&quot;topContainer&quot;]/div[@class=&quot;rightContainer&quot;]/div[@class=&quot;searchFieldContainer&quot;]/div[@class=&quot;searchField focusing&quot;]/table[@class=&quot;containerTable&quot;]/tbody[1]/tr[1]/td[@class=&quot;inputColumn&quot;]/div[@class=&quot;cellWrapper&quot;]/input[1]</value>
      <webElementGuid>8e354cb4-009b-4292-b75e-17641e0e9e79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>045c3a35-095e-4380-9e4c-aebad54cbc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='taskListBlock']/div/div[2]/div[2]/div/div/table/tbody/tr/td/div/input</value>
      <webElementGuid>929aab88-a04e-4b86-a82b-d16ac7211da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/table/tbody/tr/td/div/input</value>
      <webElementGuid>60f2f594-6c76-48c7-bd9f-52da5d92696d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Start typing name ...']</value>
      <webElementGuid>deedb271-aedf-4c01-af67-6c6b5c8c9aa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
