<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_19</name>
   <tag></tag>
   <elementGuidId>85251f99-d2c2-4006-9f51-a84146a9680f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ext-gen115']/tbody/tr[2]/td/table/tbody/tr[4]/td[5]/a/em/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.x-date-active.x-date-today.x-date-selected > a.x-date-date > em > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d3ae30a7-4456-4f8e-9058-4a6251939311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>d59ce1f1-9f4c-4f13-a5b5-63ccee4d66f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen115&quot;)/tbody[1]/tr[2]/td[1]/table[@class=&quot;x-date-inner&quot;]/tbody[1]/tr[4]/td[@class=&quot;x-date-active x-date-today x-date-selected&quot;]/a[@class=&quot;x-date-date&quot;]/em[1]/span[1]</value>
      <webElementGuid>e1d03260-20bb-44b1-8a36-180892292acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9cb2467c-a861-428a-8ec0-2dff1f325b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>7398266f-e40a-4e76-986d-e5b81acf41b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen115&quot;)/tbody[1]/tr[2]/td[1]/table[@class=&quot;x-date-inner&quot;]/tbody[1]/tr[4]/td[@class=&quot;x-date-active x-date-today x-date-selected&quot;]/a[@class=&quot;x-date-date&quot;]/em[1]/span[1]</value>
      <webElementGuid>58810f76-31b9-491b-aac3-343cc42c7798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ext-gen115']/tbody/tr[2]/td/table/tbody/tr[4]/td[5]/a/em/span</value>
      <webElementGuid>d20764e3-6cf1-47a2-a02b-a6a43ef8eebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::span[26]</value>
      <webElementGuid>3e617846-4d41-42b7-a0f4-3ebf7c5c115c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/following::span[27]</value>
      <webElementGuid>3c89555e-3fe3-480a-bf23-37fec81afd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[29]/preceding::span[17]</value>
      <webElementGuid>b5c573f9-5ec4-467a-af72-24638e6bbaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='19']/parent::*</value>
      <webElementGuid>92ffb16c-4cc2-490f-9f7c-af9dabebf51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/a/em/span</value>
      <webElementGuid>23007989-2749-499d-b0ab-518d8b4a6eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '19' or . = '19')]</value>
      <webElementGuid>ff384e4b-7149-4795-9f22-801157f73816</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
