<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_</name>
   <tag></tag>
   <elementGuidId>d4b2d18a-5f42-4a05-951d-dc5ccb947735</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='editDescriptionPopupText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#editDescriptionPopupText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8deff7fd-4d6c-4d1f-9625-0e32c2e65deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comment</value>
      <webElementGuid>c4a60b44-6eb0-4b82-acd7-1fc50b52e55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wrap</name>
      <type>Main</type>
      <value>virtual</value>
      <webElementGuid>85953f29-f61f-4bf4-8d10-9dd0c74e1e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editDescriptionPopupText</value>
      <webElementGuid>0fa59493-d7a9-4d15-b630-1f64d6c8ae94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>1df35992-9bb8-4614-bdfe-bcaffaf12778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>controlBorder</value>
      <webElementGuid>fc228f4b-cb29-428f-a3ae-20407d2746de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing description ...</value>
      <webElementGuid>ab42c199-8474-4a5a-bba1-ea7b554fc9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>handleDescriptionChange(this)</value>
      <webElementGuid>a5d3070e-f4b9-4573-8f84-f7d2a9c10f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>handleDescriptionChange(this)</value>
      <webElementGuid>004972ae-bd41-44b0-b59c-4a5de70dccc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>handleDescriptionChange(this)</value>
      <webElementGuid>96103c24-5fcc-403d-9445-2e402865bd90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>c182d6e7-9668-44a1-bf38-b7d995d5d1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editDescriptionPopupText&quot;)</value>
      <webElementGuid>2cf426ca-0f02-4d7b-b780-6ede4bc08e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>aca4582f-a0c3-4a0b-91bd-9f9bd015450e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comment</value>
      <webElementGuid>764b41af-1d26-446f-adb4-d85b51973617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wrap</name>
      <type>Main</type>
      <value>virtual</value>
      <webElementGuid>36019302-84fa-4d96-82c3-4c9f492c2329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editDescriptionPopupText</value>
      <webElementGuid>d1ebfcb7-0e26-44ce-954b-3a5bae9b7480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>51ac521a-27be-4ed1-9dbd-e4b20a2de705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>controlBorder</value>
      <webElementGuid>9b112d88-7635-4c99-890d-6fc0b75de9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing description ...</value>
      <webElementGuid>a534bce2-a6b5-4c9c-8279-650f4b6e7a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>handleDescriptionChange(this)</value>
      <webElementGuid>469d35d5-b012-480b-979b-f9b77def1d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>handleDescriptionChange(this)</value>
      <webElementGuid>b4d1d68e-d063-48ac-a66b-bba19f0aebf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>handleDescriptionChange(this)</value>
      <webElementGuid>e7108870-63a4-43f5-9ab6-6588b0ce6188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>6d55c832-6a6c-4f6a-809b-28b60ca5e8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editDescriptionPopupText&quot;)</value>
      <webElementGuid>cab79406-c7a7-4f92-9b5d-0bd32635d4ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='editDescriptionPopupText']</value>
      <webElementGuid>0bf3d34f-9b73-4a68-bda2-1582a8ed80b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='editDescriptionPopupEditingState']/textarea</value>
      <webElementGuid>c9c2eba1-8902-4d16-9680-35c3ff33a6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Task Description'])[1]/following::textarea[1]</value>
      <webElementGuid>b16df3aa-84a4-4758-9732-6de9d56b6f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading ...'])[1]/following::textarea[1]</value>
      <webElementGuid>226d7245-9083-4e1d-8f4b-46bc827aaee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saving ...'])[1]/preceding::textarea[1]</value>
      <webElementGuid>60f110cc-02bc-4cfa-8fed-2857450b45a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading ...'])[2]/preceding::textarea[1]</value>
      <webElementGuid>85db13af-95d1-417b-b941-1aea7dd1306b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a51407ef-bbe3-40c0-81f6-0cc41a279c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'comment' and @id = 'editDescriptionPopupText' and @placeholder = 'Start typing description ...' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>ea3af91a-04ef-4570-bbf1-31071b9341c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
