<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address type HomeOffice_add_type</name>
   <tag></tag>
   <elementGuidId>5829b50a-70f3-4342-87dc-d2d06e62b40b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='add_type']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'add_type' and @type = 'radio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;add_type&quot;]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>beef74e7-f258-40c0-8793-b6dd76ab3890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add_type</value>
      <webElementGuid>5d474356-bc7a-491e-827e-858a9c9cb76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b10d7377-4e4e-4e81-a59a-222e8063d17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>2c036bf3-74b6-4df4-896a-8c8260158ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-content1&quot;)/form[1]/input[9]</value>
      <webElementGuid>b65add76-d932-45d3-b477-8e9f02ef6a4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='add_type']</value>
      <webElementGuid>85df1d23-bc0d-488a-a343-b21227672a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-content1']/form/input[9]</value>
      <webElementGuid>0bc66635-dde6-490a-acbe-d6ab5e94f5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[9]</value>
      <webElementGuid>3f25588e-b481-4b37-93cd-07c8169b90be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'add_type' and @type = 'radio']</value>
      <webElementGuid>1f04d47e-b9be-4e1e-a405-723f308b1572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
