<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>545747bc-2ca3-44ba-b9ee-e87604067700</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;submit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Sign up']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbddeca7-e9de-4106-ba1c-1a65c97968d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3d25ea08-6c63-41dd-8a5d-0f8b9557cce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign up</value>
      <webElementGuid>c1b566ed-63b9-4272-87af-74c813f510e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-content1&quot;)/form[1]/div[@class=&quot;btn&quot;]/input[2]</value>
      <webElementGuid>0457042c-561a-4c9d-b191-107b98963dff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Sign up']</value>
      <webElementGuid>3ffef3ef-1919-4b15-9237-59b79036879b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-content1']/form/div/input[2]</value>
      <webElementGuid>c6f2342c-5b34-4c47-9728-f31827a77b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>41c44566-f350-4b55-af3b-0e913c67e990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>1ecfd71c-219d-41d8-8bfd-f2fe0bb38f24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
